<a href="https://colab.research.google.com/github/jahid289/machine_learning/blob/main/machine_learning_mathamatics_IIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Date: = 12/08/22
1. **vectors**

In [ ]:
# import numpy library
import numpy as np

In [ ]:
#vector define
v1 = np.array([2,-4,6])
v2 = np.array([1,3,-3])
print(f"The vector v1 is {v1}", end = "\n\n")
print(f"The vector v2 is {v2}")


The vector v1 is [ 2 -4  6]

The vector v2 is [ 1  3 -3]


In [ ]:
# calculate the length of the vector
# length1 = sqrt(x1**2 + y1**2 + z1**2) 
# length2 = sqrt(x2**2 + y2**2 + z2**2) 

l1 = np.linalg.norm(v1)
l2 = np.linalg.norm(v2)

print(f" The length of the vector v1 is : {l1} (scaler)", end="\n\n")
print(f" The length of the vector v2 is : {l2} (scaler)")

 The length of the vector v1 is : 7.483314773547883 (scaler) 

 The length of the vector v2 is : 4.358898943540674 (scaler)


In [ ]:
# Addition of two vectors.
x = v1 + v2
print(f"The additon value of two vectors v1 & v2 is:  {x}", end="\n\n")

# vector substraction.
y = v1 - v2
print(f"The substruction value of two vector v1 & v2 is : {y}", end="\n\n")

# Multyply a vector with a scaler value . 

sm = 3*v1
print(f"The scaler multiplication of the vector v1 with the scaler value 3 is : {sm} ", end="\n\n")

The additon value of two vectors v1 & v2 is:  [ 3 -1  3]

The substruction value of two vector v1 & v2 is : [ 1 -7  9]

The scaler multiplication of the vector v1 with the scaler value 3 is : [  6 -12  18] 



In [ ]:
# Dot product of two vector
dp = np.dot(v1, v2)
print(v1)
print(v2)
print(f"The dot product of two vector v1 & v2 is: {dp}")

[ 2 -4  6]
[ 1  3 -3]
The dot product of two vector v1 & v2 is: -28


**Matrix:**

In [ ]:
#Defining of two matrixes 
matrix1 = np.array([[2,4,6],[5,6,7],[3,7,8]])
matrix2 = np.array([[3,5,6],[3,9,9],[2,5,9]]) 
print(f"The first matrix is {matrix1}", end='\n\n')
print(f"The second matrix is {matrix2}", end= '\n\n')

mtx_add = matrix1 + matrix2
print(f"The addition of two matrix is {mtx_add}" , end='\n\n')


The first matrix is [[2 4 6]
 [5 6 7]
 [3 7 8]]

The second matrix is [[3 5 6]
 [3 9 9]
 [2 5 9]]

The addition of two matrix is [[ 5  9 12]
 [ 8 15 16]
 [ 5 12 17]]



In [ ]:
# matrix multiplication :
multipication = np.matrix.dot(matrix1 , matrix2)
print(multipication)

[[ 30  76 102]
 [ 47 114 147]
 [ 46 118 153]]


In [ ]:
# matrix ,multipication of (m x n)  $  (n x m)  matrix by using numpy.matmul(argument1, argument2 )
m1 = np.array([[2,3],[7,3],[1,3]])
m2 = np.array([[1,5,2],[3,2,3]])
mn = np.matmul(m1, m2)
print(mn)

[[11 16 13]
 [16 41 23]
 [10 11 11]]


In [1]:
print("jahid Bin Alam")

jahid Bin Alam
